# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDY1ZjdkOTNhNmMxMzFhOGQ0MWIwNWQ3MTAzODhkMjZkZGVmZTMzODk1NGQ1MmUyYWY5NGRkZTI1NDExOTliZjI5MmVkOTU5NGM0MjE5M2FiYWMxM2VkZmFkZWZhN2UzZTI3YzdmOTExOTY3ZjBjYWFhMzlhOTgxNzNiNjA2ZGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
